/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as MurojaatRouteImport } from './routes/murojaat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMurojaatlarRouteImport } from './routes/admin.murojaatlar'
import { Route as AdminContentRouteImport } from './routes/admin.content'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const MurojaatRoute = MurojaatRouteImport.update({
  id: '/murojaat',
  path: '/murojaat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMurojaatlarRoute = AdminMurojaatlarRouteImport.update({
  id: '/murojaatlar',
  path: '/murojaatlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/murojaat': typeof MurojaatRoute
  '/trust': typeof TrustRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/murojaatlar': typeof AdminMurojaatlarRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/murojaat': typeof MurojaatRoute
  '/trust': typeof TrustRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/murojaatlar': typeof AdminMurojaatlarRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/murojaat': typeof MurojaatRoute
  '/trust': typeof TrustRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/murojaatlar': typeof AdminMurojaatlarRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/murojaat'
    | '/trust'
    | '/admin/content'
    | '/admin/murojaatlar'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/murojaat'
    | '/trust'
    | '/admin/content'
    | '/admin/murojaatlar'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/murojaat'
    | '/trust'
    | '/admin/content'
    | '/admin/murojaatlar'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MurojaatRoute: typeof MurojaatRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/murojaat': {
      id: '/murojaat'
      path: '/murojaat'
      fullPath: '/murojaat'
      preLoaderRoute: typeof MurojaatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/murojaatlar': {
      id: '/admin/murojaatlar'
      path: '/murojaatlar'
      fullPath: '/admin/murojaatlar'
      preLoaderRoute: typeof AdminMurojaatlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminMurojaatlarRoute: typeof AdminMurojaatlarRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminMurojaatlarRoute: AdminMurojaatlarRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MurojaatRoute: MurojaatRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
