/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MurojaatRouteImport } from './routes/murojaat'
import { Route as IndexRouteImport } from './routes/index'

const MurojaatRoute = MurojaatRouteImport.update({
  id: '/murojaat',
  path: '/murojaat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/murojaat': typeof MurojaatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/murojaat': typeof MurojaatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/murojaat': typeof MurojaatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/murojaat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/murojaat'
  id: '__root__' | '/' | '/murojaat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MurojaatRoute: typeof MurojaatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/murojaat': {
      id: '/murojaat'
      path: '/murojaat'
      fullPath: '/murojaat'
      preLoaderRoute: typeof MurojaatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MurojaatRoute: MurojaatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
